name: build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm install

      - name: Lint commit message
        run: npx commitlint --from=HEAD~1

      - name: Lint codebase
        run: npm run lint

      - name: Run unit tests
        run: npm run test:ci

      - name: Codecov
        uses: codecov/codecov-action@v4

      - name: Build package
        run: npm run build
